/*
  Dilarang keras menggandakan/mengcopy/menyebarkan/membajak/mendecompile 
  Software ini dalam bentuk apapun tanpa seijin pembuat software
  (Khanza.Soft Media). Bagi yang sengaja membajak softaware ini ta
  npa ijin, kami sumpahi sial 1000 turunan, miskin sampai 500 turu
  nan. Selalu mendapat kecelakaan sampai 400 turunan. Anak pertama
  nya cacat tidak punya kaki sampai 300 turunan. Susah cari jodoh
  sampai umur 50 tahun sampai 200 turunan. Ya Alloh maafkan kami 
  karena telah berdoa buruk, semua ini kami lakukan karena kami ti
  dak pernah rela karya kami dibajak tanpa ijin.
 */
package khanzaantrianloket;
import chrriis.dj.nativeswing.swtimpl.NativeInterface;
import chrriis.dj.nativeswing.swtimpl.components.JWebBrowser;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.akses;
import java.awt.BorderLayout;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Toolkit;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.FileInputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Properties;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import java.awt.event.KeyListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javafx.application.Platform;
import javafx.beans.value.ChangeListener;
import javafx.beans.value.ObservableValue;
import javafx.concurrent.Worker;
import static javafx.concurrent.Worker.State.FAILED;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.web.PopupFeatures;
import javafx.scene.web.WebEngine;
import javafx.scene.web.WebEvent;
import javafx.scene.web.WebView;
import javafx.stage.Stage;
import javafx.stage.StageStyle;
import javafx.util.Callback;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.border.EmptyBorder;
import javax.swing.event.DocumentEvent;
import static mondrian.olap.fun.vba.Vba.date;
import org.apache.poi.hssf.record.PageBreakRecord;

/**
 *
 * @author perpustakaan
 */
public class frmUtama extends javax.swing.JFrame {
    private final Connection koneksi = koneksiDB.condb();
    private final sekuel Sequel = new sekuel();
    private final validasi Valid = new validasi();
    private static frmUtama myInstance;
    private final Properties prop = new Properties();
    private SimpleDateFormat dateformat = new SimpleDateFormat("yyyy/MM/dd");
    private SimpleDateFormat dateformat2 = new SimpleDateFormat("yyyy-MM-dd");
    private Date date = new Date();
    private String now = dateformat2.format(date);
    private String urlNya = "", jamShutdown = "", jamPasnya = "", tglReset = "";
    private int i = 0;
    private WebEngine engine;
    private final JPanel panel = new JPanel(new BorderLayout());
    private final JFXPanel jfxPanel = new JFXPanel();    
    
    public frmUtama(java.awt.Frame parent, boolean modal) {
//        super(parent, modal);
        initComponents(); 
        setIconImage(new ImageIcon(super.getClass().getResource("/picture/LaST (Cobalt) My Network.png")).getImage());
        jam();
        
        //ini kalimat berjalan  
        kalimat_info.setText(Sequel.cariIsi("select kalimat from antrian_informasi where kode=1"));
        Timer timer = new Timer(270, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {                
                String teksAsli = kalimat_info.getText();
                String teksBaru = teksAsli.substring(1) + teksAsli.substring(0, 1);
                kalimat_info.setText(teksBaru);
            }
        });
        timer.start();
        //sampai disini

        //menampilkan video youtube
        urlNya = Sequel.cariIsi("select url_video_player from antrian_informasi where kode='1'");
        try {
            loadURL(urlNya);
            initComponents2();
        } catch (Exception ex) {
            System.out.println("Notifikasi : " + ex);
        }

        try {
            prop.loadFromXML(new FileInputStream("setting/database.xml"));
        } catch (Exception e) {
            System.out.println("SEP XML : "+e);
        }
    }
    
    /**
     * Creates new form frmUtama
     */
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        MnTutupAplikasi = new javax.swing.JMenuItem();
        MnRefresKalimat = new javax.swing.JMenuItem();
        MnBrowserEdge = new javax.swing.JMenuItem();
        internalFrame2 = new widget.InternalFrame();
        PanelWall = new usu.widget.glass.PanelGlass();
        judul = new javax.swing.JLabel();
        internalFrame4 = new widget.InternalFrame();
        internalFrame6 = new widget.InternalFrame();
        internalFrame7 = new widget.InternalFrame();
        internalFrame9 = new widget.InternalFrame();
        internalFrame14 = new widget.InternalFrame();
        no_bpjs = new javax.swing.JLabel();
        internalFrame15 = new widget.InternalFrame();
        loket_bpjs = new javax.swing.JLabel();
        internalFrame10 = new widget.InternalFrame();
        internalFrame16 = new widget.InternalFrame();
        no_khusus = new javax.swing.JLabel();
        internalFrame17 = new widget.InternalFrame();
        loket_khusus = new javax.swing.JLabel();
        internalFrame11 = new widget.InternalFrame();
        internalFrame12 = new widget.InternalFrame();
        internalFrame18 = new widget.InternalFrame();
        no_umum = new javax.swing.JLabel();
        internalFrame19 = new widget.InternalFrame();
        loket_umum = new javax.swing.JLabel();
        internalFrame13 = new widget.InternalFrame();
        tgljam = new javax.swing.JLabel();
        internalFrame8 = new widget.InternalFrame();
        kalimat_info = new javax.swing.JLabel();

        jPopupMenu1.setForeground(new java.awt.Color(60, 80, 50));
        jPopupMenu1.setName("jPopupMenu1"); // NOI18N

        MnTutupAplikasi.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        MnTutupAplikasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        MnTutupAplikasi.setText("Tutup Aplikasi");
        MnTutupAplikasi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MnTutupAplikasi.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        MnTutupAplikasi.setIconTextGap(5);
        MnTutupAplikasi.setName("MnTutupAplikasi"); // NOI18N
        MnTutupAplikasi.setPreferredSize(new java.awt.Dimension(180, 26));
        MnTutupAplikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnTutupAplikasiActionPerformed(evt);
            }
        });
        jPopupMenu1.add(MnTutupAplikasi);

        MnRefresKalimat.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        MnRefresKalimat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/category.png"))); // NOI18N
        MnRefresKalimat.setText("Refresh Kalimat Informasi");
        MnRefresKalimat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MnRefresKalimat.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        MnRefresKalimat.setIconTextGap(5);
        MnRefresKalimat.setName("MnRefresKalimat"); // NOI18N
        MnRefresKalimat.setPreferredSize(new java.awt.Dimension(180, 26));
        MnRefresKalimat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnRefresKalimatActionPerformed(evt);
            }
        });
        jPopupMenu1.add(MnRefresKalimat);

        MnBrowserEdge.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        MnBrowserEdge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/microsoft-edge-16.png"))); // NOI18N
        MnBrowserEdge.setText("Microsoft Edge");
        MnBrowserEdge.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MnBrowserEdge.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        MnBrowserEdge.setIconTextGap(5);
        MnBrowserEdge.setName("MnBrowserEdge"); // NOI18N
        MnBrowserEdge.setPreferredSize(new java.awt.Dimension(180, 26));
        MnBrowserEdge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnBrowserEdgeActionPerformed(evt);
            }
        });
        jPopupMenu1.add(MnBrowserEdge);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("::[ Monitor Antrian ]::");
        setIconImages(null);
        setUndecorated(true);
        setResizable(false);
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        internalFrame2.setBorder(null);
        internalFrame2.setComponentPopupMenu(jPopupMenu1);
        internalFrame2.setName("internalFrame2"); // NOI18N
        internalFrame2.setPreferredSize(new java.awt.Dimension(0, 130));
        internalFrame2.setLayout(new java.awt.BorderLayout(1, 1));

        PanelWall.setBackground(new java.awt.Color(29, 29, 29));
        PanelWall.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/wallpaper_atas.png"))); // NOI18N
        PanelWall.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        PanelWall.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 0, 0, 0));
        PanelWall.setPreferredSize(new java.awt.Dimension(200, 200));
        PanelWall.setRound(false);
        PanelWall.setWarna(new java.awt.Color(110, 110, 110));
        PanelWall.setLayout(new java.awt.BorderLayout(0, 10));

        judul.setFont(new java.awt.Font("Tahoma", 1, 55)); // NOI18N
        judul.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        judul.setText("Antrian Pendaftaran Rawat Jalan   ");
        judul.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        judul.setName("judul"); // NOI18N
        judul.setPreferredSize(new java.awt.Dimension(10000, 23));
        PanelWall.add(judul, java.awt.BorderLayout.CENTER);

        internalFrame2.add(PanelWall, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame2, java.awt.BorderLayout.PAGE_START);

        internalFrame4.setBorder(null);
        internalFrame4.setName("internalFrame4"); // NOI18N
        internalFrame4.setLayout(new java.awt.BorderLayout(1, 1));

        internalFrame6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Courtesy on Youtube Channel RSU Nirwana ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        internalFrame6.setName("internalFrame6"); // NOI18N
        internalFrame6.setPreferredSize(new java.awt.Dimension(700, 1200));
        internalFrame6.setLayout(new java.awt.BorderLayout());
        internalFrame4.add(internalFrame6, java.awt.BorderLayout.CENTER);

        internalFrame7.setBorder(null);
        internalFrame7.setName("internalFrame7"); // NOI18N
        internalFrame7.setPreferredSize(new java.awt.Dimension(480, 1200));
        internalFrame7.setLayout(new java.awt.BorderLayout(1, 1));

        internalFrame9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " BPJS KESEHATAN ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 30), new java.awt.Color(0, 153, 0))); // NOI18N
        internalFrame9.setName("internalFrame9"); // NOI18N
        internalFrame9.setPreferredSize(new java.awt.Dimension(300, 250));
        internalFrame9.setWarnaBawah(new java.awt.Color(127, 220, 34));
        internalFrame9.setLayout(new java.awt.BorderLayout(1, 1));

        internalFrame14.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), " NO. ANTRIAN ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 153, 0))); // NOI18N
        internalFrame14.setName("internalFrame14"); // NOI18N
        internalFrame14.setPreferredSize(new java.awt.Dimension(300, 250));
        internalFrame14.setWarnaBawah(new java.awt.Color(127, 220, 34));
        internalFrame14.setLayout(new java.awt.BorderLayout(1, 1));

        no_bpjs.setFont(new java.awt.Font("Tahoma", 1, 170)); // NOI18N
        no_bpjs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        no_bpjs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        no_bpjs.setName("no_bpjs"); // NOI18N
        no_bpjs.setPreferredSize(new java.awt.Dimension(100, 23));
        internalFrame14.add(no_bpjs, java.awt.BorderLayout.CENTER);

        internalFrame9.add(internalFrame14, java.awt.BorderLayout.CENTER);

        internalFrame15.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), " DI LOKET ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 153, 0))); // NOI18N
        internalFrame15.setName("internalFrame15"); // NOI18N
        internalFrame15.setPreferredSize(new java.awt.Dimension(120, 250));
        internalFrame15.setWarnaBawah(new java.awt.Color(127, 220, 34));
        internalFrame15.setLayout(new java.awt.BorderLayout(1, 1));

        loket_bpjs.setFont(new java.awt.Font("Tahoma", 1, 160)); // NOI18N
        loket_bpjs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loket_bpjs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loket_bpjs.setName("loket_bpjs"); // NOI18N
        loket_bpjs.setPreferredSize(new java.awt.Dimension(100, 23));
        internalFrame15.add(loket_bpjs, java.awt.BorderLayout.CENTER);

        internalFrame9.add(internalFrame15, java.awt.BorderLayout.LINE_END);

        internalFrame7.add(internalFrame9, java.awt.BorderLayout.PAGE_START);

        internalFrame10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " KHUSUS / PRIORITAS ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 30), new java.awt.Color(153, 0, 153))); // NOI18N
        internalFrame10.setName("internalFrame10"); // NOI18N
        internalFrame10.setPreferredSize(new java.awt.Dimension(300, 300));
        internalFrame10.setWarnaBawah(new java.awt.Color(235, 117, 235));
        internalFrame10.setLayout(new java.awt.BorderLayout(1, 1));

        internalFrame16.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), " NO. ANTRIAN ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(153, 0, 153))); // NOI18N
        internalFrame16.setName("internalFrame16"); // NOI18N
        internalFrame16.setPreferredSize(new java.awt.Dimension(300, 300));
        internalFrame16.setWarnaBawah(new java.awt.Color(235, 117, 235));
        internalFrame16.setLayout(new java.awt.BorderLayout(1, 1));

        no_khusus.setFont(new java.awt.Font("Tahoma", 1, 170)); // NOI18N
        no_khusus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        no_khusus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        no_khusus.setName("no_khusus"); // NOI18N
        no_khusus.setPreferredSize(new java.awt.Dimension(100, 23));
        internalFrame16.add(no_khusus, java.awt.BorderLayout.CENTER);

        internalFrame10.add(internalFrame16, java.awt.BorderLayout.CENTER);

        internalFrame17.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), " DI LOKET ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(153, 0, 153))); // NOI18N
        internalFrame17.setName("internalFrame17"); // NOI18N
        internalFrame17.setPreferredSize(new java.awt.Dimension(120, 300));
        internalFrame17.setWarnaBawah(new java.awt.Color(235, 117, 235));
        internalFrame17.setLayout(new java.awt.BorderLayout(1, 1));

        loket_khusus.setFont(new java.awt.Font("Tahoma", 1, 160)); // NOI18N
        loket_khusus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loket_khusus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loket_khusus.setName("loket_khusus"); // NOI18N
        loket_khusus.setPreferredSize(new java.awt.Dimension(100, 23));
        internalFrame17.add(loket_khusus, java.awt.BorderLayout.CENTER);

        internalFrame10.add(internalFrame17, java.awt.BorderLayout.LINE_END);

        internalFrame7.add(internalFrame10, java.awt.BorderLayout.CENTER);

        internalFrame11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " UMUM (NON BPJS) ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 30))); // NOI18N
        internalFrame11.setName("internalFrame11"); // NOI18N
        internalFrame11.setPreferredSize(new java.awt.Dimension(300, 308));
        internalFrame11.setLayout(new java.awt.BorderLayout(1, 1));

        internalFrame12.setBorder(null);
        internalFrame12.setName("internalFrame12"); // NOI18N
        internalFrame12.setPreferredSize(new java.awt.Dimension(300, 300));
        internalFrame12.setWarnaBawah(new java.awt.Color(204, 204, 204));
        internalFrame12.setLayout(new java.awt.BorderLayout(1, 1));

        internalFrame18.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), " NO. ANTRIAN ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        internalFrame18.setName("internalFrame18"); // NOI18N
        internalFrame18.setPreferredSize(new java.awt.Dimension(300, 300));
        internalFrame18.setWarnaBawah(new java.awt.Color(204, 204, 204));
        internalFrame18.setLayout(new java.awt.BorderLayout(1, 1));

        no_umum.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        no_umum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        no_umum.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        no_umum.setName("no_umum"); // NOI18N
        no_umum.setPreferredSize(new java.awt.Dimension(100, 23));
        internalFrame18.add(no_umum, java.awt.BorderLayout.CENTER);

        internalFrame12.add(internalFrame18, java.awt.BorderLayout.CENTER);

        internalFrame19.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), " DI LOKET ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        internalFrame19.setName("internalFrame19"); // NOI18N
        internalFrame19.setPreferredSize(new java.awt.Dimension(120, 300));
        internalFrame19.setWarnaBawah(new java.awt.Color(204, 204, 204));
        internalFrame19.setLayout(new java.awt.BorderLayout(1, 1));

        loket_umum.setFont(new java.awt.Font("Tahoma", 1, 160)); // NOI18N
        loket_umum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loket_umum.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loket_umum.setName("loket_umum"); // NOI18N
        loket_umum.setPreferredSize(new java.awt.Dimension(100, 23));
        internalFrame19.add(loket_umum, java.awt.BorderLayout.CENTER);

        internalFrame12.add(internalFrame19, java.awt.BorderLayout.LINE_END);

        internalFrame11.add(internalFrame12, java.awt.BorderLayout.CENTER);

        internalFrame13.setBorder(null);
        internalFrame13.setName("internalFrame13"); // NOI18N
        internalFrame13.setPreferredSize(new java.awt.Dimension(300, 50));
        internalFrame13.setWarnaAtas(new java.awt.Color(204, 204, 204));
        internalFrame13.setLayout(new java.awt.BorderLayout(1, 1));

        tgljam.setFont(new java.awt.Font("Tahoma", 1, 37)); // NOI18N
        tgljam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tgljam.setText("Tanggal & Jam");
        tgljam.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tgljam.setName("tgljam"); // NOI18N
        tgljam.setPreferredSize(new java.awt.Dimension(100, 23));
        internalFrame13.add(tgljam, java.awt.BorderLayout.CENTER);

        internalFrame11.add(internalFrame13, java.awt.BorderLayout.PAGE_END);

        internalFrame7.add(internalFrame11, java.awt.BorderLayout.PAGE_END);

        internalFrame4.add(internalFrame7, java.awt.BorderLayout.LINE_END);

        getContentPane().add(internalFrame4, java.awt.BorderLayout.CENTER);

        internalFrame8.setBorder(null);
        internalFrame8.setName("internalFrame8"); // NOI18N
        internalFrame8.setPreferredSize(new java.awt.Dimension(0, 120));
        internalFrame8.setWarnaBawah(new java.awt.Color(156, 200, 20));
        internalFrame8.setLayout(new java.awt.BorderLayout(1, 1));

        kalimat_info.setFont(new java.awt.Font("Tahoma", 1, 93)); // NOI18N
        kalimat_info.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kalimat_info.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        kalimat_info.setName("kalimat_info"); // NOI18N
        kalimat_info.setPreferredSize(new java.awt.Dimension(10000, 23));
        internalFrame8.add(kalimat_info, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame8, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        kalimat_info.setText(Sequel.cariIsi("select kalimat from antrian_informasi where kode=1"));        
    }//GEN-LAST:event_formWindowActivated

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        if(this.isActive()==false){
            Platform.setImplicitExit(false);
        }
    }//GEN-LAST:event_formWindowStateChanged

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Platform.setImplicitExit(false);
    }//GEN-LAST:event_formWindowClosed

    private void MnTutupAplikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnTutupAplikasiActionPerformed
        i = JOptionPane.showConfirmDialog(null, "Apakah aplikasi ini akan ditutup..??", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (i == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_MnTutupAplikasiActionPerformed

    private void MnRefresKalimatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnRefresKalimatActionPerformed
        kalimat_info.setText(Sequel.cariIsi("select kalimat from antrian_informasi where kode=1"));
        Timer timer = new Timer(270, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String teksAsli = kalimat_info.getText();
                String teksBaru = teksAsli.substring(1) + teksAsli.substring(0, 1);
                kalimat_info.setText(teksBaru);
            }
        });
        timer.start();
    }//GEN-LAST:event_MnRefresKalimatActionPerformed

    private void MnBrowserEdgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnBrowserEdgeActionPerformed
        try {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            Runtime.getRuntime().exec("C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe");
            this.setCursor(Cursor.getDefaultCursor());
        } catch (Exception e) {
            System.out.print("Notifikasi : "+e);
        }
    }//GEN-LAST:event_MnBrowserEdgeActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnBrowserEdge;
    private javax.swing.JMenuItem MnRefresKalimat;
    private javax.swing.JMenuItem MnTutupAplikasi;
    private usu.widget.glass.PanelGlass PanelWall;
    private widget.InternalFrame internalFrame10;
    private widget.InternalFrame internalFrame11;
    private widget.InternalFrame internalFrame12;
    private widget.InternalFrame internalFrame13;
    private widget.InternalFrame internalFrame14;
    private widget.InternalFrame internalFrame15;
    private widget.InternalFrame internalFrame16;
    private widget.InternalFrame internalFrame17;
    private widget.InternalFrame internalFrame18;
    private widget.InternalFrame internalFrame19;
    private widget.InternalFrame internalFrame2;
    private widget.InternalFrame internalFrame4;
    private widget.InternalFrame internalFrame6;
    private widget.InternalFrame internalFrame7;
    private widget.InternalFrame internalFrame8;
    private widget.InternalFrame internalFrame9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel kalimat_info;
    private javax.swing.JLabel loket_bpjs;
    private javax.swing.JLabel loket_khusus;
    private javax.swing.JLabel loket_umum;
    private javax.swing.JLabel no_bpjs;
    private javax.swing.JLabel no_khusus;
    private javax.swing.JLabel no_umum;
    private javax.swing.JLabel tgljam;
    // End of variables declaration//GEN-END:variables

    public void cekHariLibur() {        
        if (Sequel.cariInteger("select count(1) from hari_libur where tgl_libur = date(now())") > 0) {
            try {
                Runtime runtime = Runtime.getRuntime();
                Process proc = runtime.exec("shutdown -s -t 10");
                System.exit(0);
            } catch (Exception e) {
            }
            
        } else if (Sequel.cariInteger("select count(1) from hari_libur where tgl_libur = date(now())") == 0) {
            tglReset = "";
            if (Sequel.cariInteger("select count(1) from hari_libur where tgl_libur = date(now())") > 0) {
                tglReset = now;
            } else if (Sequel.cariInteger("select count(1) from hari_libur where tgl_libur = date(now())") == 0) {
                tglReset = Sequel.cariIsi("SELECT date(tgl_reset) from antrian_history_reset where jenis_reset like '%resep%' order by tgl_reset desc limit 1");
            }

            //semua nomor antrian direset mundur 2 hari        
            resetPanggilanAntrian();
            resetNomorAntrian();
            Sequel.queryu("delete from antrian_history_reset where date(tgl_reset) < DATE_FORMAT(date_sub(now(), interval 2 day),'%Y-%m-%d')");
            Sequel.queryu("delete from antrian_prioritas where date(waktu_simpan) < DATE_FORMAT(date_sub(now(), interval 2 day),'%Y-%m-%d')");
        }
    }
    
    private void isTutup() {
        akses.setform("frmUtama");
        Window[] wins = Window.getWindows();
        for (Window win : wins) {
            if (win instanceof JDialog) {
                win.dispose();
            }
        }
    }
    
    private void jam() {
        ActionListener taskPerformer = new ActionListener() {
            private int nilai_jam;
            private int nilai_menit;
            private int nilai_detik;

            public void actionPerformed(ActionEvent e) {
                String nol_jam = "";
                String nol_menit = "";
                String nol_detik = "";                

                Date now = Calendar.getInstance().getTime();

                // Mengambil nilaj JAM, MENIT, dan DETIK Sekarang
                    nilai_jam = now.getHours();
                    nilai_menit = now.getMinutes();
                    nilai_detik = now.getSeconds();

                // Jika nilai JAM lebih kecil dari 10 (hanya 1 digit)
                if (nilai_jam <= 9) {
                    // Tambahkan "0" didepannya
                    nol_jam = "0";
                }
                // Jika nilai MENIT lebih kecil dari 10 (hanya 1 digit)
                if (nilai_menit <= 9) {
                    // Tambahkan "0" didepannya
                    nol_menit = "0";
                }
                // Jika nilai DETIK lebih kecil dari 10 (hanya 1 digit)
                if (nilai_detik <= 9) {
                    // Tambahkan "0" didepannya
                    nol_detik = "0";
                }
                // Membuat String JAM, MENIT, DETIK
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                jamPasnya = jam + ":" + menit + ":" + detik;                
                komputerDimatikan();
                
                // Menampilkan pada Layar
                tgljam.setText(Sequel.cariIsi("SELECT date_format(now(),'%d-%m-%Y')") + " || " + jam + ":" + menit + ":" + detik);
                
                no_bpjs.setText(Sequel.cariIsi("SELECT no_antrian FROM antrian_pemanggil_bpjs where "
                        + "date(waktu_panggil)=date(now()) ORDER BY no_antrian DESC LIMIT 1"));
                loket_bpjs.setText(Sequel.cariIsi("SELECT diloket FROM antrian_pemanggil_bpjs where "
                        + "date(waktu_panggil)=date(now()) ORDER BY no_antrian DESC LIMIT 1"));

                no_khusus.setText(Sequel.cariIsi("SELECT no_antrian FROM antrian_pemanggil_lansia where "
                        + "date(waktu_panggil)=date(now()) ORDER BY no_antrian DESC LIMIT 1"));
                loket_khusus.setText(Sequel.cariIsi("SELECT diloket FROM antrian_pemanggil_lansia where "
                        + "date(waktu_panggil)=date(now()) ORDER BY no_antrian DESC LIMIT 1"));

                no_umum.setText(Sequel.cariIsi("SELECT concat('PU-',no_antrian) FROM antrian_pemanggil_umum where "
                        + "date(waktu_panggil)=date(now()) ORDER BY no_antrian DESC LIMIT 1"));
                loket_umum.setText(Sequel.cariIsi("SELECT diloket FROM antrian_pemanggil_umum where "
                        + "date(waktu_panggil)=date(now()) ORDER BY no_antrian DESC LIMIT 1"));
            }
        };
        // Timer
        new Timer(1000, taskPerformer).start();
    }
    
    private void createScene() {   
        urlNya = "";
        urlNya = Sequel.cariIsi("select url_video_player from antrian_informasi where kode='1'");
        Platform.runLater(new Runnable() {

            public void run() {
                WebView view = new WebView();
                
                engine = view.getEngine();
                engine.setJavaScriptEnabled(true);
                
                engine.setCreatePopupHandler(new Callback<PopupFeatures, WebEngine>() {
                    @Override
                    public WebEngine call(PopupFeatures p) {
                        Stage stage = new Stage(StageStyle.TRANSPARENT);
                        return view.getEngine();
                    }
                });
                
                engine.getLoadWorker().exceptionProperty().addListener((ObservableValue<? extends Throwable> o, Throwable old, final Throwable value) -> {
                    if (engine.getLoadWorker().getState() == FAILED) {
                        SwingUtilities.invokeLater(() -> {
                            JOptionPane.showMessageDialog(
                                    panel,
                                    (value != null) ?
                                            engine.getLocation() + "\n" + value.getMessage() :
                                            engine.getLocation() + "\nUnexpected Video.",
                                    "Loading Video...",
                                    JOptionPane.ERROR_MESSAGE);
                        });
                    }
                });                
                
                engine.getLoadWorker().stateProperty().addListener(new ChangeListener<Worker.State>() {
                    @Override
                    public void changed(ObservableValue ov, Worker.State oldState, Worker.State newState) {
                        if (newState == Worker.State.SUCCEEDED) {
                            try {
                                if (engine.getLocation().replaceAll(urlNya, "").contains(urlNya)) {
                                    setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                                    Valid.panggilUrl(engine.getLocation().replaceAll(urlNya, ""));
                                    engine.executeScript("history.back()");
                                    setCursor(Cursor.getDefaultCursor());
                                } else if (engine.getLocation().replaceAll(urlNya, "").contains(urlNya)) {
                                    dispose();                                    
                                }
                            } catch (Exception ex) {
                                System.out.println("Notifikasi : "+ex);
                            }
                        } 
                    }
                });
                
                jfxPanel.setScene(new Scene(view));
            }
        });
    }
   
    public void loadURL(String url) {
        try {            
            createScene();
        } catch (Exception e) {
        }

        Platform.runLater(() -> {
            try {
                engine.load(url);
            } catch (Exception exception) {
                engine.load(url);
            }
        });
    }
    
    private void initComponents2() {           
        panel.add(jfxPanel, BorderLayout.CENTER);        
        internalFrame6.setLayout(new BorderLayout());
        internalFrame6.add(panel);
    }
    
    private void resetPanggilanAntrian() {
        //panggilan bpjs
        if (Sequel.cariInteger("select count(-1) from antrian_pemanggil_bpjs where date(waktu_panggil)=date('" + tglReset + "')") > 0) {
            Sequel.menyimpan("antrian_history_reset", "'Panggilan Antrian BPJS',"
                    + "'" + Sequel.cariIsi("select no_antrian from antrian_pemanggil_bpjs where date(waktu_panggil)=date('" + tglReset + "') order by no_antrian desc limit 1") + "',"
                    + "'" + Sequel.cariIsi("SELECT tgl_reset from antrian_history_reset where jenis_reset like '%resep%' order by tgl_reset desc limit 1") + "'", "Nomor Antrian Panggilan BPJS");   
            Sequel.queryu("delete from antrian_pemanggil_bpjs where date(waktu_panggil) < DATE_FORMAT(date_sub(now(), interval 2 day),'%Y-%m-%d')");
        }

        //panggilan khusus
        if (Sequel.cariInteger("select count(-1) from antrian_pemanggil_lansia where date(waktu_panggil)=date('" + tglReset + "')") > 0) {
            Sequel.menyimpan("antrian_history_reset", "'Panggilan Antrian KHUSUS/PRIORITAS',"
                    + "'" + Sequel.cariIsi("select no_antrian from antrian_pemanggil_lansia where date(waktu_panggil)=date('" + tglReset + "') order by no_antrian desc limit 1") + "',"
                    + "'" + Sequel.cariIsi("SELECT tgl_reset from antrian_history_reset where jenis_reset like '%resep%' order by tgl_reset desc limit 1") + "'", "Nomor Antrian Panggilan KHUSUS/PRIORITAS");
            Sequel.queryu("delete from antrian_pemanggil_lansia where date(waktu_panggil) < DATE_FORMAT(date_sub(now(), interval 2 day),'%Y-%m-%d')");
        }

        //panggilan umum
        if (Sequel.cariInteger("select count(-1) from antrian_pemanggil_umum where date(waktu_panggil)=date('" + tglReset + "')") > 0) {
            Sequel.menyimpan("antrian_history_reset", "'Panggilan Antrian Umum',"
                    + "'" + Sequel.cariIsi("select no_antrian from antrian_pemanggil_umum where date(waktu_panggil)=date('" + tglReset + "') order by no_antrian desc limit 1") + "',"
                    + "'" + Sequel.cariIsi("SELECT tgl_reset from antrian_history_reset where jenis_reset like '%resep%' order by tgl_reset desc limit 1") + "'", "Nomor Antrian Panggilan Umum");
            Sequel.queryu("delete from antrian_pemanggil_umum where date(waktu_panggil) < DATE_FORMAT(date_sub(now(), interval 2 day),'%Y-%m-%d')");
        }

        //panggilan inap
        if (Sequel.cariInteger("select count(-1) from antrian_pemanggil_inap where date(waktu_panggil)=date('" + tglReset + "')") > 0) {
            Sequel.menyimpan("antrian_history_reset", "'Panggilan Antrian Ranap',"
                    + "'" + Sequel.cariIsi("select no_antrian from antrian_pemanggil_inap where date(waktu_panggil)=date('" + tglReset + "') order by no_antrian desc limit 1") + "',"
                    + "'" + Sequel.cariIsi("SELECT tgl_reset from antrian_history_reset where jenis_reset like '%resep%' order by tgl_reset desc limit 1") + "'", "Nomor Antrian Panggilan Ranap");
            Sequel.queryu("delete from antrian_pemanggil_inap where date(waktu_panggil) < DATE_FORMAT(date_sub(now(), interval 2 day),'%Y-%m-%d')");
        }
    }
    
    private void resetNomorAntrian() {
        //nomor umum
        if (Sequel.cariInteger("select count(-1) from antrian_nomor_umum where date(waktu_cetak)=date('" + tglReset + "')") > 0) {
            Sequel.menyimpan("antrian_history_reset", "'Nomor Antrian Umum',"
                    + "'" + Sequel.cariIsi("select no_antrian from antrian_nomor_umum where date(waktu_cetak)=date('" + tglReset + "') order by no_antrian desc limit 1") + "',"
                    + "'" + Sequel.cariIsi("SELECT tgl_reset from antrian_history_reset where jenis_reset like '%resep%' order by tgl_reset desc limit 1") + "'", "Nomor Antrian Pasien Umum");
            Sequel.queryu("delete from antrian_nomor_umum where date(waktu_cetak) < DATE_FORMAT(date_sub(now(), interval 2 day),'%Y-%m-%d')");
        }

        //nomor khusus
        if (Sequel.cariInteger("select count(-1) from antrian_nomor_lansia where date(waktu_cetak)=date('" + tglReset + "')") > 0) {
            Sequel.menyimpan("antrian_history_reset", "'Nomor Antrian KHUSUS/PRIORITAS',"
                    + "'" + Sequel.cariIsi("select no_antrian from antrian_nomor_lansia where date(waktu_cetak)=date('" + tglReset + "') order by no_antrian desc limit 1") + "',"
                    + "'" + Sequel.cariIsi("SELECT tgl_reset from antrian_history_reset where jenis_reset like '%resep%' order by tgl_reset desc limit 1") + "'", "Nomor Antrian Pasien KHUSUS/PRIORITAS");
            Sequel.queryu("delete from antrian_nomor_lansia where date(waktu_cetak) < DATE_FORMAT(date_sub(now(), interval 2 day),'%Y-%m-%d')");
        }

        //nomor bpjs
        if (Sequel.cariInteger("select count(-1) from antrian_nomor_bpjs where date(waktu_cetak)=date('" + tglReset + "')") > 0) {
            Sequel.menyimpan("antrian_history_reset", "'Nomor Antrian BPJS',"
                    + "'" + Sequel.cariIsi("select no_antrian from antrian_nomor_bpjs where date(waktu_cetak)=date('" + tglReset + "') order by no_antrian desc limit 1") + "',"
                    + "'" + Sequel.cariIsi("SELECT tgl_reset from antrian_history_reset where jenis_reset like '%resep%' order by tgl_reset desc limit 1") + "'", "Nomor Antrian Pasien BPJS");
            Sequel.queryu("delete from antrian_nomor_bpjs where date(waktu_cetak) < DATE_FORMAT(date_sub(now(), interval 2 day),'%Y-%m-%d')");
        }
        
        //nomor inap
        if (Sequel.cariInteger("select count(-1) from antrian_nomor_inap where date(waktu_cetak)=date('" + tglReset + "')") > 0) {
            Sequel.menyimpan("antrian_history_reset", "'Nomor Antrian Ranap',"
                    + "'" + Sequel.cariIsi("select no_antrian from antrian_nomor_inap where date(waktu_cetak)=date('" + tglReset + "') order by no_antrian desc limit 1") + "',"
                    + "'" + Sequel.cariIsi("SELECT tgl_reset from antrian_history_reset where jenis_reset like '%resep%' order by tgl_reset desc limit 1") + "'", "Nomor Antrian Pasien Ranap");
            Sequel.queryu("delete from antrian_nomor_inap where date(waktu_cetak) < DATE_FORMAT(date_sub(now(), interval 2 day),'%Y-%m-%d')");
        }
    }
    
    private void komputerDimatikan() {
        jamShutdown = "";        
        jamShutdown = Sequel.cariIsi("select ifnull(shutdown_tv_antrian,'15:00:00') from antrian_informasi where kode=1");        
        
        //saatnya komputer shutdown
        if (jamShutdown.equals(jamPasnya)) {            
            try {
                Runtime runtime = Runtime.getRuntime();
                Process proc = runtime.exec("shutdown -s -t 10");
                System.exit(0);
            } catch (Exception e) {
            }
        }
    }
}
