/*
  Dilarang keras menggandakan/mengcopy/menyebarkan/membajak/mendecompile 
  Software ini dalam bentuk apapun tanpa seijin pembuat software
  (Khanza.Soft Media). Bagi yang sengaja membajak softaware ini ta
  npa ijin, kami sumpahi sial 1000 turunan, miskin sampai 500 turu
  nan. Selalu mendapat kecelakaan sampai 400 turunan. Anak pertama
  nya cacat tidak punya kaki sampai 300 turunan. Susah cari jodoh
  sampai umur 50 tahun sampai 200 turunan. Ya Alloh maafkan kami 
  karena telah berdoa buruk, semua ini kami lakukan karena kami ti
  dak pernah rela karya kami dibajak tanpa ijin.
 */
package khanzaantrianloket;
import chrriis.dj.nativeswing.swtimpl.NativeInterface;
import chrriis.dj.nativeswing.swtimpl.components.JWebBrowser;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.akses;
import java.awt.BorderLayout;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Toolkit;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.FileInputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Properties;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import java.awt.event.KeyListener;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javafx.application.Platform;
import javafx.beans.value.ChangeListener;
import javafx.beans.value.ObservableValue;
import javafx.concurrent.Worker;
import static javafx.concurrent.Worker.State.FAILED;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.media.MediaPlayer;
import javafx.scene.web.PopupFeatures;
import javafx.scene.web.WebEngine;
import javafx.scene.web.WebEvent;
import javafx.scene.web.WebView;
import javafx.stage.Stage;
import javafx.stage.StageStyle;
import javafx.util.Callback;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.border.EmptyBorder;
import javax.swing.event.DocumentEvent;
import static mondrian.olap.fun.vba.Vba.date;
import org.apache.poi.hssf.record.PageBreakRecord;
import uk.co.caprica.vlcj.component.EmbeddedMediaPlayerComponent;
import uk.co.caprica.vlcj.discovery.NativeDiscovery;

/**
 *
 * @author perpustakaan
 */
public class frmUtama extends javax.swing.JFrame {
    private final Connection koneksi = koneksiDB.condb();
    private final sekuel Sequel = new sekuel();
    private final validasi Valid = new validasi();
    private static frmUtama myInstance;
    private final Properties prop = new Properties();
    private SimpleDateFormat dateformat = new SimpleDateFormat("yyyy/MM/dd");
    private SimpleDateFormat dateformat2 = new SimpleDateFormat("yyyy-MM-dd");
    private Date date = new Date();
    private String now = dateformat2.format(date);
    private String urlNya = "", jamShutdown = "", jamPasnya = "", tglReset = "";
    private int i = 0;
    private final JPanel panel = new JPanel(new BorderLayout());
    private final JFXPanel jfxPanel = new JFXPanel();
    private EmbeddedMediaPlayerComponent mediaPlayerComponent;
    
    public frmUtama(java.awt.Frame parent, boolean modal) {
//        super(parent, modal);
        initComponents();        
        setIconImage(new ImageIcon(super.getClass().getResource("/picture/LaST (Cobalt) My Network.png")).getImage());
        jam();
        
        //ini kalimat berjalan  
        kalimat_info.setText(Sequel.cariIsi("select kalimat from antrian_informasi where kode=1"));
        Timer timer = new Timer(270, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {                
                String teksAsli = kalimat_info.getText();
                String teksBaru = teksAsli.substring(1) + teksAsli.substring(0, 1);
                kalimat_info.setText(teksBaru);
            }
        });
        timer.start();
        //sampai disini

        try {
            prop.loadFromXML(new FileInputStream("setting/database.xml"));
        } catch (Exception e) {
            System.out.println("SEP XML : "+e);
        }
    }
    
    /**
     * Creates new form frmUtama
     */
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        MnTutupAplikasi = new javax.swing.JMenuItem();
        MnRefresKalimat = new javax.swing.JMenuItem();
        MnBrowserEdge = new javax.swing.JMenuItem();
        MnPengaturan = new javax.swing.JMenuItem();
        WindowPengaturan = new javax.swing.JDialog();
        internalFrame5 = new widget.InternalFrame();
        BtnClose = new widget.Button();
        jLabel38 = new widget.Label();
        TlokasiFile = new widget.TextBox();
        BtnSimpan = new widget.Button();
        jLabel39 = new widget.Label();
        Scroll3 = new widget.ScrollPane();
        Tkalimat = new widget.TextArea();
        internalFrame2 = new widget.InternalFrame();
        PanelWall = new usu.widget.glass.PanelGlass();
        judul = new javax.swing.JLabel();
        internalFrame4 = new widget.InternalFrame();
        internalFrame6 = new widget.InternalFrame();
        internalFrame7 = new widget.InternalFrame();
        internalFrame20 = new widget.InternalFrame();
        internalFrame14 = new widget.InternalFrame();
        no_antri = new javax.swing.JLabel();
        internalFrame15 = new widget.InternalFrame();
        no_loket = new javax.swing.JLabel();
        internalFrame13 = new widget.InternalFrame();
        tgljam = new javax.swing.JLabel();
        internalFrame8 = new widget.InternalFrame();
        kalimat_info = new javax.swing.JLabel();

        jPopupMenu1.setForeground(new java.awt.Color(60, 80, 50));
        jPopupMenu1.setName("jPopupMenu1"); // NOI18N

        MnTutupAplikasi.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        MnTutupAplikasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        MnTutupAplikasi.setText("Tutup Aplikasi");
        MnTutupAplikasi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MnTutupAplikasi.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        MnTutupAplikasi.setIconTextGap(5);
        MnTutupAplikasi.setName("MnTutupAplikasi"); // NOI18N
        MnTutupAplikasi.setPreferredSize(new java.awt.Dimension(180, 26));
        MnTutupAplikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnTutupAplikasiActionPerformed(evt);
            }
        });
        jPopupMenu1.add(MnTutupAplikasi);

        MnRefresKalimat.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        MnRefresKalimat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/category.png"))); // NOI18N
        MnRefresKalimat.setText("Refresh Kalimat Informasi");
        MnRefresKalimat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MnRefresKalimat.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        MnRefresKalimat.setIconTextGap(5);
        MnRefresKalimat.setName("MnRefresKalimat"); // NOI18N
        MnRefresKalimat.setPreferredSize(new java.awt.Dimension(180, 26));
        MnRefresKalimat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnRefresKalimatActionPerformed(evt);
            }
        });
        jPopupMenu1.add(MnRefresKalimat);

        MnBrowserEdge.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        MnBrowserEdge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/microsoft-edge-16.png"))); // NOI18N
        MnBrowserEdge.setText("Microsoft Edge");
        MnBrowserEdge.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MnBrowserEdge.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        MnBrowserEdge.setIconTextGap(5);
        MnBrowserEdge.setName("MnBrowserEdge"); // NOI18N
        MnBrowserEdge.setPreferredSize(new java.awt.Dimension(180, 26));
        MnBrowserEdge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnBrowserEdgeActionPerformed(evt);
            }
        });
        jPopupMenu1.add(MnBrowserEdge);

        MnPengaturan.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        MnPengaturan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/category.png"))); // NOI18N
        MnPengaturan.setText("Set Pengaturan");
        MnPengaturan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MnPengaturan.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        MnPengaturan.setIconTextGap(5);
        MnPengaturan.setName("MnPengaturan"); // NOI18N
        MnPengaturan.setPreferredSize(new java.awt.Dimension(180, 26));
        MnPengaturan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnPengaturanActionPerformed(evt);
            }
        });
        jPopupMenu1.add(MnPengaturan);

        WindowPengaturan.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        WindowPengaturan.setName("WindowPengaturan"); // NOI18N
        WindowPengaturan.setUndecorated(true);
        WindowPengaturan.setResizable(false);

        internalFrame5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3), "::[ Set Pengaturan ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        internalFrame5.setName("internalFrame5"); // NOI18N
        internalFrame5.setWarnaBawah(new java.awt.Color(245, 250, 240));
        internalFrame5.setLayout(null);

        BtnClose.setForeground(new java.awt.Color(0, 0, 0));
        BtnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cross.png"))); // NOI18N
        BtnClose.setMnemonic('U');
        BtnClose.setText("Tutup");
        BtnClose.setToolTipText("Alt+U");
        BtnClose.setName("BtnClose"); // NOI18N
        BtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCloseActionPerformed(evt);
            }
        });
        internalFrame5.add(BtnClose);
        BtnClose.setBounds(620, 170, 100, 30);

        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("Path/Lokasi File :");
        jLabel38.setName("jLabel38"); // NOI18N
        internalFrame5.add(jLabel38);
        jLabel38.setBounds(0, 135, 120, 23);

        TlokasiFile.setBackground(new java.awt.Color(245, 250, 240));
        TlokasiFile.setForeground(new java.awt.Color(0, 0, 0));
        TlokasiFile.setName("TlokasiFile"); // NOI18N
        internalFrame5.add(TlokasiFile);
        TlokasiFile.setBounds(125, 135, 600, 23);

        BtnSimpan.setForeground(new java.awt.Color(0, 0, 0));
        BtnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/save-16x16.png"))); // NOI18N
        BtnSimpan.setMnemonic('S');
        BtnSimpan.setText("Simpan");
        BtnSimpan.setToolTipText("Alt+S");
        BtnSimpan.setName("BtnSimpan"); // NOI18N
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });
        internalFrame5.add(BtnSimpan);
        BtnSimpan.setBounds(510, 170, 100, 30);

        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("Kalimat Run Text :");
        jLabel39.setName("jLabel39"); // NOI18N
        internalFrame5.add(jLabel39);
        jLabel39.setBounds(0, 20, 120, 23);

        Scroll3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Scroll3.setName("Scroll3"); // NOI18N

        Tkalimat.setColumns(20);
        Tkalimat.setRows(5);
        Tkalimat.setName("Tkalimat"); // NOI18N
        Tkalimat.setPreferredSize(new java.awt.Dimension(170, 2000));
        Tkalimat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TkalimatKeyPressed(evt);
            }
        });
        Scroll3.setViewportView(Tkalimat);

        internalFrame5.add(Scroll3);
        Scroll3.setBounds(125, 20, 600, 110);

        WindowPengaturan.getContentPane().add(internalFrame5, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("::[ Monitor Antrian ]::");
        setIconImages(null);
        setUndecorated(true);
        setResizable(false);
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame2.setBorder(null);
        internalFrame2.setComponentPopupMenu(jPopupMenu1);
        internalFrame2.setName("internalFrame2"); // NOI18N
        internalFrame2.setPreferredSize(new java.awt.Dimension(0, 130));
        internalFrame2.setLayout(new java.awt.BorderLayout(1, 1));

        PanelWall.setBackground(new java.awt.Color(29, 29, 29));
        PanelWall.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/wallpaper_atas.png"))); // NOI18N
        PanelWall.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        PanelWall.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 0, 0, 0));
        PanelWall.setPreferredSize(new java.awt.Dimension(200, 200));
        PanelWall.setRound(false);
        PanelWall.setWarna(new java.awt.Color(110, 110, 110));
        PanelWall.setLayout(new java.awt.BorderLayout(0, 10));

        judul.setFont(new java.awt.Font("Tahoma", 1, 55)); // NOI18N
        judul.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        judul.setText("Antrian Pendaftaran Rawat Jalan   ");
        judul.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        judul.setName("judul"); // NOI18N
        judul.setPreferredSize(new java.awt.Dimension(10000, 23));
        PanelWall.add(judul, java.awt.BorderLayout.CENTER);

        internalFrame2.add(PanelWall, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame2, java.awt.BorderLayout.PAGE_START);

        internalFrame4.setBorder(null);
        internalFrame4.setName("internalFrame4"); // NOI18N
        internalFrame4.setLayout(new java.awt.BorderLayout(1, 1));

        internalFrame6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Courtesy on Youtube Channel RSU Nirwana ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        internalFrame6.setName("internalFrame6"); // NOI18N
        internalFrame6.setPreferredSize(new java.awt.Dimension(700, 1200));
        internalFrame6.setLayout(new java.awt.BorderLayout());
        internalFrame4.add(internalFrame6, java.awt.BorderLayout.CENTER);

        internalFrame7.setBorder(null);
        internalFrame7.setName("internalFrame7"); // NOI18N
        internalFrame7.setPreferredSize(new java.awt.Dimension(400, 1200));
        internalFrame7.setLayout(new java.awt.BorderLayout(1, 1));

        internalFrame20.setName("internalFrame20"); // NOI18N
        internalFrame20.setPreferredSize(new java.awt.Dimension(300, 250));
        internalFrame20.setWarnaBawah(new java.awt.Color(127, 220, 34));
        internalFrame20.setLayout(new java.awt.GridLayout(2, 1));

        internalFrame14.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), " NO. ANTRIAN ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 45), new java.awt.Color(0, 153, 0))); // NOI18N
        internalFrame14.setName("internalFrame14"); // NOI18N
        internalFrame14.setPreferredSize(new java.awt.Dimension(300, 250));
        internalFrame14.setWarnaBawah(new java.awt.Color(127, 220, 34));
        internalFrame14.setLayout(new java.awt.BorderLayout(1, 1));

        no_antri.setFont(new java.awt.Font("Tahoma", 1, 190)); // NOI18N
        no_antri.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        no_antri.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        no_antri.setName("no_antri"); // NOI18N
        no_antri.setPreferredSize(new java.awt.Dimension(100, 23));
        internalFrame14.add(no_antri, java.awt.BorderLayout.CENTER);

        internalFrame20.add(internalFrame14);

        internalFrame15.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), " DI LOKET ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 50), new java.awt.Color(0, 153, 0))); // NOI18N
        internalFrame15.setName("internalFrame15"); // NOI18N
        internalFrame15.setPreferredSize(new java.awt.Dimension(120, 250));
        internalFrame15.setWarnaBawah(new java.awt.Color(127, 220, 34));
        internalFrame15.setLayout(new java.awt.BorderLayout(1, 1));

        no_loket.setFont(new java.awt.Font("Tahoma", 1, 250)); // NOI18N
        no_loket.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        no_loket.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        no_loket.setName("no_loket"); // NOI18N
        no_loket.setPreferredSize(new java.awt.Dimension(100, 23));
        internalFrame15.add(no_loket, java.awt.BorderLayout.CENTER);

        internalFrame20.add(internalFrame15);

        internalFrame7.add(internalFrame20, java.awt.BorderLayout.CENTER);

        internalFrame13.setBorder(null);
        internalFrame13.setName("internalFrame13"); // NOI18N
        internalFrame13.setPreferredSize(new java.awt.Dimension(300, 50));
        internalFrame13.setWarnaAtas(new java.awt.Color(127, 220, 34));
        internalFrame13.setLayout(new java.awt.BorderLayout(1, 1));

        tgljam.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        tgljam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tgljam.setText("Tanggal & Jam");
        tgljam.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tgljam.setName("tgljam"); // NOI18N
        tgljam.setPreferredSize(new java.awt.Dimension(100, 23));
        internalFrame13.add(tgljam, java.awt.BorderLayout.CENTER);

        internalFrame7.add(internalFrame13, java.awt.BorderLayout.PAGE_END);

        internalFrame4.add(internalFrame7, java.awt.BorderLayout.LINE_END);

        getContentPane().add(internalFrame4, java.awt.BorderLayout.CENTER);

        internalFrame8.setBorder(null);
        internalFrame8.setName("internalFrame8"); // NOI18N
        internalFrame8.setPreferredSize(new java.awt.Dimension(0, 120));
        internalFrame8.setWarnaBawah(new java.awt.Color(127, 220, 34));
        internalFrame8.setLayout(new java.awt.BorderLayout(1, 1));

        kalimat_info.setFont(new java.awt.Font("Tahoma", 1, 93)); // NOI18N
        kalimat_info.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kalimat_info.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        kalimat_info.setName("kalimat_info"); // NOI18N
        kalimat_info.setPreferredSize(new java.awt.Dimension(10000, 23));
        internalFrame8.add(kalimat_info, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame8, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        kalimat_info.setText(Sequel.cariIsi("select kalimat from antrian_informasi where kode=1"));        
    }//GEN-LAST:event_formWindowActivated

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        if(this.isActive()==false){
            Platform.setImplicitExit(false);
        }
    }//GEN-LAST:event_formWindowStateChanged

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Platform.setImplicitExit(false);
    }//GEN-LAST:event_formWindowClosed

    private void MnTutupAplikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnTutupAplikasiActionPerformed
        i = JOptionPane.showConfirmDialog(null, "Apakah aplikasi ini akan ditutup..??", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (i == JOptionPane.YES_OPTION) {
            tutupVLC();
            WindowPengaturan.dispose();
            System.exit(0);
        }
    }//GEN-LAST:event_MnTutupAplikasiActionPerformed

    private void MnRefresKalimatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnRefresKalimatActionPerformed
        kalimat_info.setText(Sequel.cariIsi("select kalimat from antrian_informasi where kode=1"));
        Timer timer = new Timer(270, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String teksAsli = kalimat_info.getText();
                String teksBaru = teksAsli.substring(1) + teksAsli.substring(0, 1);
                kalimat_info.setText(teksBaru);
            }
        });
        timer.start();
    }//GEN-LAST:event_MnRefresKalimatActionPerformed

    private void MnBrowserEdgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnBrowserEdgeActionPerformed
        try {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            Runtime.getRuntime().exec("C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe");
            this.setCursor(Cursor.getDefaultCursor());
        } catch (Exception e) {
            System.out.print("Notifikasi : "+e);
        }
    }//GEN-LAST:event_MnBrowserEdgeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        initVideo();
    }//GEN-LAST:event_formWindowOpened

    private void BtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCloseActionPerformed
        WindowPengaturan.dispose();
    }//GEN-LAST:event_BtnCloseActionPerformed

    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
        if (Sequel.mengedittf("antrian_informasi", "kode=?", "kalimat=?, lokasi_file_video=?", 3, new String[]{
            " " + Tkalimat.getText(), TlokasiFile.getText(), "1"
        }) == true) {
            WindowPengaturan.dispose();
            MnRefresKalimatActionPerformed(null);
            JOptionPane.showMessageDialog(null,"Set pengaturan berhasil, jika memperbaiki lokasi file video tutup aplikasi lalu buka lagi..!");            
        }
    }//GEN-LAST:event_BtnSimpanActionPerformed

    private void TkalimatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TkalimatKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            TlokasiFile.requestFocus();
        }        
    }//GEN-LAST:event_TkalimatKeyPressed

    private void MnPengaturanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnPengaturanActionPerformed
        WindowPengaturan.setSize(762, 221);
        WindowPengaturan.setLocationRelativeTo(internalFrame6);
        WindowPengaturan.setVisible(true);
        
        Tkalimat.setText(Sequel.cariIsi("select kalimat from antrian_informasi where kode='1'"));
        TlokasiFile.setText(Sequel.cariIsi("select lokasi_file_video from antrian_informasi where kode='1'"));
    }//GEN-LAST:event_MnPengaturanActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnClose;
    private widget.Button BtnSimpan;
    private javax.swing.JMenuItem MnBrowserEdge;
    private javax.swing.JMenuItem MnPengaturan;
    private javax.swing.JMenuItem MnRefresKalimat;
    private javax.swing.JMenuItem MnTutupAplikasi;
    private usu.widget.glass.PanelGlass PanelWall;
    private widget.ScrollPane Scroll3;
    public widget.TextArea Tkalimat;
    private widget.TextBox TlokasiFile;
    private javax.swing.JDialog WindowPengaturan;
    private widget.InternalFrame internalFrame13;
    private widget.InternalFrame internalFrame14;
    private widget.InternalFrame internalFrame15;
    private widget.InternalFrame internalFrame2;
    private widget.InternalFrame internalFrame20;
    private widget.InternalFrame internalFrame4;
    private widget.InternalFrame internalFrame5;
    private widget.InternalFrame internalFrame6;
    private widget.InternalFrame internalFrame7;
    private widget.InternalFrame internalFrame8;
    private widget.Label jLabel38;
    private widget.Label jLabel39;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel kalimat_info;
    private javax.swing.JLabel no_antri;
    private javax.swing.JLabel no_loket;
    private javax.swing.JLabel tgljam;
    // End of variables declaration//GEN-END:variables

    public void cekHariLibur() {        
        if (Sequel.cariInteger("select count(1) from hari_libur where tgl_libur = date(now())") > 0) {
            try {
                Runtime runtime = Runtime.getRuntime();
                Process proc = runtime.exec("shutdown -s -t 10");
                System.exit(0);
            } catch (Exception e) {
            }
            
        } else if (Sequel.cariInteger("select count(1) from hari_libur where tgl_libur = date(now())") == 0) {
            tglReset = "";
            if (Sequel.cariInteger("select count(1) from hari_libur where tgl_libur = date(now())") > 0) {
                tglReset = now;
            } else if (Sequel.cariInteger("select count(1) from hari_libur where tgl_libur = date(now())") == 0) {
                tglReset = Sequel.cariIsi("SELECT date(tgl_reset) from antrian_history_reset where jenis_reset like '%resep%' order by tgl_reset desc limit 1");
            }

            //semua nomor antrian direset mundur 2 hari        
            resetPanggilanAntrian();
            resetNomorAntrian();
            Sequel.queryu("delete from antrian_history_reset where date(tgl_reset) < DATE_FORMAT(date_sub(now(), interval 2 day),'%Y-%m-%d')");
            Sequel.queryu("delete from antrian_prioritas where date(waktu_simpan) < DATE_FORMAT(date_sub(now(), interval 2 day),'%Y-%m-%d')");
        }
    }
    
    private void isTutup() {
        akses.setform("frmUtama");
        Window[] wins = Window.getWindows();
        for (Window win : wins) {
            if (win instanceof JDialog) {
                win.dispose();
            }
        }
    }
    
    private void jam() {
        ActionListener taskPerformer = new ActionListener() {
            private int nilai_jam;
            private int nilai_menit;
            private int nilai_detik;

            public void actionPerformed(ActionEvent e) {
                String nol_jam = "";
                String nol_menit = "";
                String nol_detik = "";                

                Date now = Calendar.getInstance().getTime();

                // Mengambil nilaj JAM, MENIT, dan DETIK Sekarang
                    nilai_jam = now.getHours();
                    nilai_menit = now.getMinutes();
                    nilai_detik = now.getSeconds();

                // Jika nilai JAM lebih kecil dari 10 (hanya 1 digit)
                if (nilai_jam <= 9) {
                    // Tambahkan "0" didepannya
                    nol_jam = "0";
                }
                // Jika nilai MENIT lebih kecil dari 10 (hanya 1 digit)
                if (nilai_menit <= 9) {
                    // Tambahkan "0" didepannya
                    nol_menit = "0";
                }
                // Jika nilai DETIK lebih kecil dari 10 (hanya 1 digit)
                if (nilai_detik <= 9) {
                    // Tambahkan "0" didepannya
                    nol_detik = "0";
                }
                // Membuat String JAM, MENIT, DETIK
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                jamPasnya = jam + ":" + menit + ":" + detik;                
//                komputerDimatikan();
                
                // Menampilkan pada Layar
                tgljam.setText(Sequel.cariIsi("SELECT date_format(now(),'%d-%m-%Y')") + " || " + jam + ":" + menit + ":" + detik);
                
                no_antri.setText(Sequel.cariIsi("SELECT no_antrian FROM antrian_pemanggil where "
                        + "date(waktu_panggil)=date(now()) ORDER BY no_antrian DESC LIMIT 1"));
                no_loket.setText(Sequel.cariIsi("SELECT diloket FROM antrian_pemanggil where "
                        + "date(waktu_panggil)=date(now()) ORDER BY no_antrian DESC LIMIT 1"));
            }
        };
        // Timer
        new Timer(1000, taskPerformer).start();
    }
    
    private void resetPanggilanAntrian() {
        //panggilan bpjs
        if (Sequel.cariInteger("select count(-1) from antrian_pemanggil_bpjs where date(waktu_panggil)=date('" + tglReset + "')") > 0) {
            Sequel.menyimpan("antrian_history_reset", "'Panggilan Antrian BPJS',"
                    + "'" + Sequel.cariIsi("select no_antrian from antrian_pemanggil_bpjs where date(waktu_panggil)=date('" + tglReset + "') order by no_antrian desc limit 1") + "',"
                    + "'" + Sequel.cariIsi("SELECT tgl_reset from antrian_history_reset where jenis_reset like '%resep%' order by tgl_reset desc limit 1") + "'", "Nomor Antrian Panggilan BPJS");   
            Sequel.queryu("delete from antrian_pemanggil_bpjs where date(waktu_panggil) < DATE_FORMAT(date_sub(now(), interval 2 day),'%Y-%m-%d')");
        }

        //panggilan khusus
        if (Sequel.cariInteger("select count(-1) from antrian_pemanggil_lansia where date(waktu_panggil)=date('" + tglReset + "')") > 0) {
            Sequel.menyimpan("antrian_history_reset", "'Panggilan Antrian KHUSUS/PRIORITAS',"
                    + "'" + Sequel.cariIsi("select no_antrian from antrian_pemanggil_lansia where date(waktu_panggil)=date('" + tglReset + "') order by no_antrian desc limit 1") + "',"
                    + "'" + Sequel.cariIsi("SELECT tgl_reset from antrian_history_reset where jenis_reset like '%resep%' order by tgl_reset desc limit 1") + "'", "Nomor Antrian Panggilan KHUSUS/PRIORITAS");
            Sequel.queryu("delete from antrian_pemanggil_lansia where date(waktu_panggil) < DATE_FORMAT(date_sub(now(), interval 2 day),'%Y-%m-%d')");
        }

        //panggilan umum
        if (Sequel.cariInteger("select count(-1) from antrian_pemanggil_umum where date(waktu_panggil)=date('" + tglReset + "')") > 0) {
            Sequel.menyimpan("antrian_history_reset", "'Panggilan Antrian Umum',"
                    + "'" + Sequel.cariIsi("select no_antrian from antrian_pemanggil_umum where date(waktu_panggil)=date('" + tglReset + "') order by no_antrian desc limit 1") + "',"
                    + "'" + Sequel.cariIsi("SELECT tgl_reset from antrian_history_reset where jenis_reset like '%resep%' order by tgl_reset desc limit 1") + "'", "Nomor Antrian Panggilan Umum");
            Sequel.queryu("delete from antrian_pemanggil_umum where date(waktu_panggil) < DATE_FORMAT(date_sub(now(), interval 2 day),'%Y-%m-%d')");
        }

        //panggilan inap
        if (Sequel.cariInteger("select count(-1) from antrian_pemanggil_inap where date(waktu_panggil)=date('" + tglReset + "')") > 0) {
            Sequel.menyimpan("antrian_history_reset", "'Panggilan Antrian Ranap',"
                    + "'" + Sequel.cariIsi("select no_antrian from antrian_pemanggil_inap where date(waktu_panggil)=date('" + tglReset + "') order by no_antrian desc limit 1") + "',"
                    + "'" + Sequel.cariIsi("SELECT tgl_reset from antrian_history_reset where jenis_reset like '%resep%' order by tgl_reset desc limit 1") + "'", "Nomor Antrian Panggilan Ranap");
            Sequel.queryu("delete from antrian_pemanggil_inap where date(waktu_panggil) < DATE_FORMAT(date_sub(now(), interval 2 day),'%Y-%m-%d')");
        }
    }
    
    private void resetNomorAntrian() {
        //nomor umum
        if (Sequel.cariInteger("select count(-1) from antrian_nomor_umum where date(waktu_cetak)=date('" + tglReset + "')") > 0) {
            Sequel.menyimpan("antrian_history_reset", "'Nomor Antrian Umum',"
                    + "'" + Sequel.cariIsi("select no_antrian from antrian_nomor_umum where date(waktu_cetak)=date('" + tglReset + "') order by no_antrian desc limit 1") + "',"
                    + "'" + Sequel.cariIsi("SELECT tgl_reset from antrian_history_reset where jenis_reset like '%resep%' order by tgl_reset desc limit 1") + "'", "Nomor Antrian Pasien Umum");
            Sequel.queryu("delete from antrian_nomor_umum where date(waktu_cetak) < DATE_FORMAT(date_sub(now(), interval 2 day),'%Y-%m-%d')");
        }

        //nomor khusus
        if (Sequel.cariInteger("select count(-1) from antrian_nomor_lansia where date(waktu_cetak)=date('" + tglReset + "')") > 0) {
            Sequel.menyimpan("antrian_history_reset", "'Nomor Antrian KHUSUS/PRIORITAS',"
                    + "'" + Sequel.cariIsi("select no_antrian from antrian_nomor_lansia where date(waktu_cetak)=date('" + tglReset + "') order by no_antrian desc limit 1") + "',"
                    + "'" + Sequel.cariIsi("SELECT tgl_reset from antrian_history_reset where jenis_reset like '%resep%' order by tgl_reset desc limit 1") + "'", "Nomor Antrian Pasien KHUSUS/PRIORITAS");
            Sequel.queryu("delete from antrian_nomor_lansia where date(waktu_cetak) < DATE_FORMAT(date_sub(now(), interval 2 day),'%Y-%m-%d')");
        }

        //nomor bpjs
        if (Sequel.cariInteger("select count(-1) from antrian_nomor_bpjs where date(waktu_cetak)=date('" + tglReset + "')") > 0) {
            Sequel.menyimpan("antrian_history_reset", "'Nomor Antrian BPJS',"
                    + "'" + Sequel.cariIsi("select no_antrian from antrian_nomor_bpjs where date(waktu_cetak)=date('" + tglReset + "') order by no_antrian desc limit 1") + "',"
                    + "'" + Sequel.cariIsi("SELECT tgl_reset from antrian_history_reset where jenis_reset like '%resep%' order by tgl_reset desc limit 1") + "'", "Nomor Antrian Pasien BPJS");
            Sequel.queryu("delete from antrian_nomor_bpjs where date(waktu_cetak) < DATE_FORMAT(date_sub(now(), interval 2 day),'%Y-%m-%d')");
        }
        
        //nomor inap
        if (Sequel.cariInteger("select count(-1) from antrian_nomor_inap where date(waktu_cetak)=date('" + tglReset + "')") > 0) {
            Sequel.menyimpan("antrian_history_reset", "'Nomor Antrian Ranap',"
                    + "'" + Sequel.cariIsi("select no_antrian from antrian_nomor_inap where date(waktu_cetak)=date('" + tglReset + "') order by no_antrian desc limit 1") + "',"
                    + "'" + Sequel.cariIsi("SELECT tgl_reset from antrian_history_reset where jenis_reset like '%resep%' order by tgl_reset desc limit 1") + "'", "Nomor Antrian Pasien Ranap");
            Sequel.queryu("delete from antrian_nomor_inap where date(waktu_cetak) < DATE_FORMAT(date_sub(now(), interval 2 day),'%Y-%m-%d')");
        }
    }
    
    private void komputerDimatikan() {
        jamShutdown = "";        
        jamShutdown = Sequel.cariIsi("select ifnull(shutdown_tv_antrian,'15:00:00') from antrian_informasi where kode=1");        
        
        //saatnya komputer shutdown
        if (jamShutdown.equals(jamPasnya)) {            
            try {
                Runtime runtime = Runtime.getRuntime();
                Process proc = runtime.exec("shutdown -s -t 10");
                System.exit(0);
            } catch (Exception e) {
            }
        }
    }

    public void initVideo() {
        try {
            String os = System.getProperty("os.name").toLowerCase();
            if (os.contains("win")) {
                System.setProperty("jna.library.path", "C:\\Program Files\\VideoLAN\\VLC");
            } else {
                System.setProperty("jna.library.path", "/usr/lib/x86_64-linux-gnu");
            }

            new NativeDiscovery().discover();

            //Ambil path video dari DB
            String mediaPath = Sequel.cariIsi("select lokasi_file_video from antrian_informasi where kode='1'");

            if (mediaPath == null || mediaPath.trim().isEmpty()) {
                JOptionPane.showMessageDialog(null,"Path video kosong di database...!");
                return;
            }

            File videoFile = new File(mediaPath);

            if (!videoFile.exists()) {
                JOptionPane.showMessageDialog(null,"File video tidak ditemukan/ada kesalahan dalam penulisan lokasi file/path :      \n" + mediaPath);
                return;
            }

            //Inisialisasi player
            final EmbeddedMediaPlayerComponent mediaPlayerComponent = new EmbeddedMediaPlayerComponent();
            internalFrame6.removeAll();
            internalFrame6.setLayout(new BorderLayout());
            internalFrame6.add(mediaPlayerComponent, BorderLayout.CENTER);
            internalFrame6.revalidate();
            internalFrame6.repaint();
            internalFrame6.setVisible(true);
            
            //Play video pertama
            mediaPlayerComponent.getMediaPlayer().playMedia(mediaPath);

            //Loop manual jika selesai
            mediaPlayerComponent.getMediaPlayer()
                    .addMediaPlayerEventListener(
                            new uk.co.caprica.vlcj.player.MediaPlayerEventAdapter() {
                        @Override
                        public void finished(
                                uk.co.caprica.vlcj.player.MediaPlayer mediaPlayer) {
                            mediaPlayer.playMedia(mediaPath);
                        }
                        @Override
                        public void error(
                                uk.co.caprica.vlcj.player.MediaPlayer mediaPlayer) {
                            System.out.println("Terjadi kesalahan saat memutar video..!");
                        }
                    });
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,"Terjadi kesalahan saat memutar video..!");
        }
    }
    
    private void tutupVLC() {
        if (mediaPlayerComponent != null) {
            mediaPlayerComponent.release();
        }
        super.dispose();
    }
}
